name: wp-cli-command-scaffold-groot
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    run:
      - bin/dev-setup.sh
tooling:
  test:
    service: appserver
    cmd: vendor/bin/phpunit
  unit:
    service: appserver
    cmd: vendor/bin/phpunit --group unit
  e2e:
    service: appserver
    cmd: vendor/bin/phpunit --group e2e
  setup:
    service: appserver
    cmd:
      - bin/dev-setup.sh
  clean:
    service: appserver
    cmd: rm -rf vendor/ wp/

