sudo: false
dist: trusty

language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE wordpress;'

install:
  - composer install
  - vendor/bin/wp core download --path=wp
  - vendor/bin/wp config create --dbname=wordpress --dbuser=travis --dbpass='' --dbhost=127.0.0.1
  - vendor/bin/wp core install --url=http://localhost/ --title='Groot Scaffold' --admin_user=lando --admin_email=lando@example.com

script:
  - vendor/bin/phpunit --group unit
  - vendor/bin/phpunit --group e2e

matrix:
  allow_failures:
    - php: '7.4'
