sudo: false
dist: trusty

language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - vendor/bin/phpunit
